{"timestamp":"2025-05-14T10:06:34.540288","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-14T10:06:34.548907","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/prediccion_ventas_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-14T10:06:35.337542Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.338643Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.339192Z","level":"info","event":"Current task name:generar_clima_futuro","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.339682Z","level":"info","event":"Dag name:prediccion_ventas_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.383748","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/prediccion_pipeline.py","lineno":41,"name":"generate_future_weather"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3008,"name":"to_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":787,"name":"to_sql"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":851,"name":"pandasSQL_builder"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py","lineno":1576,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":96,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3404,"name":"raw_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3374,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2208,"name":"_handle_dbapi_exception_noconnection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]},{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}]}]}
{"timestamp":"2025-05-14T10:06:35.396627Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.397341Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.397942Z","level":"info","event":"Task:<Task(PythonOperator): generar_clima_futuro>","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.398530Z","level":"info","event":"Failure caused by (psycopg2.OperationalError) connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.399104Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.399708Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.400280Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.400866Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-05-14T10:06:35.401410Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
